# Generated by Django 2.0.6 on 2018-07-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20180715_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='last_update',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
